# Generated by Django 4.0.4 on 2022-05-21 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edgpress', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
