# Generated by Django 4.0.4 on 2022-05-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edgpress', '0004_article_comment_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sub',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
